name: build

on: push

env:
  GROUP: weaveworksdemos
  REPO: catalogue
  COMMIT: ${{ github.sha }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_NAME: ghcr.io/${{ github.repository }}
  PUSH_DOCKER: false

jobs:
  test:
    defaults:
      run:
        working-directory: go/src/github.com/microservices-demo/catalogue
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.7.5
      GOPATH: /home/runner/work/catalogue/catalogue/go

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/microservices-demo/catalogue

      - name: Set default Docker tag 'test'
        run: |
          echo "DOCKER_TAG=test" >> $GITHUB_ENV
      - name: Use branch name as Docker tag
        if: startsWith(github.ref, 'refs/heads')
        run: |
          echo "Using branch name as docker tag"
          echo "DOCKER_TAG=$(echo ${{ github.ref }} | sed -e "s|refs/heads/||g" | sed -e "s|/|.|g")" >> $GITHUB_ENV
      - name: Use 'latest' as Docker tag
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Using latest as docker tag"
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
      - name: Use tag name as Docker tag
        if: startsWith(github.ref, 'refs/tags')
        run: |
          echo "Using git tag as docker tag"
          echo "DOCKER_TAG=$(echo ${{ github.ref }} | sed -e "s|refs/tags/||g")" >> $GITHUB_ENV

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup PATH
        run: echo "${GOPATH}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: go get -u github.com/FiloSottile/gvt && gvt restore && go get -v github.com/mattn/goveralls

      - name: Build
        run: ./scripts/build.sh

#      - name: Unit Test
#        run: ./test/test.sh unit.py

#      - name: Test Docker Image
#        run: ./test/test.sh container.py

#      - name: Submit Coveralls
#        env:
#          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: goveralls -coverprofile=coverage.out -service=github

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        if: env.PUSH_DOCKER_IMAGE == 'true'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Build and push catalogue to ghcr.io
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          file: go/src/github.com/microservices-demo/catalogue/docker/catalogue/Dockerfile
          context: go/src/github.com/microservices-demo/catalogue
          tags: |
            ${{ env.DOCKER_NAME }}:latest
            ${{ env.DOCKER_NAME }}:${{ env.DOCKER_TAG }}
          push: ${{ env.PUSH_DOCKER_IMAGE }}

      - name: Build and push catalogue DB to ghcr.io
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          file: go/src/github.com/microservices-demo/catalogue/docker/catalogue-db/Dockerfile
          context: go/src/github.com/microservices-demo/catalogue/docker/catalogue-db
          tags: |
            ${{ env.DOCKER_NAME }}-db:latest
            ${{ env.DOCKER_NAME }}-db:${{ env.DOCKER_TAG }}
          push: ${{ env.PUSH_DOCKER_IMAGE }}
